import { chromium } from 'playwright';
const HOST='https://fishlogger-client.vercel.app';
const OUT=new URL('./shots/', import.meta.url).pathname;
const b=await chromium.launch({ channel: 'chromium', args: ['--disable-blink-features=AutomationControlled'] });
const ctx=await b.newContext({userAgent:'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',viewport:{width:1440,height:1000},permissions:['geolocation'],geolocation:{latitude:-34.13,longitude:18.33}});
const p=await ctx.newPage();
const passChallenge=async(page)=>{ for(let i=0;i<10;i++){ if(!/Security Checkpoint/.test(await page.title())) return; await page.waitForTimeout(1500);} };
await p.goto(HOST+'/sign-in',{waitUntil:'load',timeout:60000}); await passChallenge(p);
await p.fill('input[type=email]','owen@fishlogger.app'); await p.fill('input[type=password]','TestAngler2026!');
await p.click('button[type=submit]'); await p.waitForTimeout(3500);
await p.goto(HOST+'/',{waitUntil:'load',timeout:60000}); await passChallenge(p); await p.waitForTimeout(7000);
console.log('HOME', JSON.stringify(await p.evaluate(()=>({lastAt:[...document.querySelectorAll('header p')].map(x=>x.textContent).find(t=>/Last at/.test(t||'')), says:[...document.querySelectorAll('p')].map(x=>x.textContent).find(t=>/catches at|only catch at|logged/.test(t||''))}))));
await p.goto(HOST+'/insights',{waitUntil:'load',timeout:60000}); await passChallenge(p); await p.waitForTimeout(3000);
console.log('INSIGHTS', JSON.stringify(await p.evaluate(()=>{const card=document.querySelector('.blk.self-start'); const col=card?.parentElement?.children[1]; return {fishs:document.body.innerText.includes('fishs'), cardH:card?Math.round(card.getBoundingClientRect().height):null, colH:col?Math.round(col.getBoundingClientRect().height):null};})));
await p.screenshot({path:`${OUT}v16-insights.png`, clip:{x:0,y:0,width:1440,height:900}});
await p.goto(HOST+'/map',{waitUntil:'load',timeout:60000}); await passChallenge(p); await p.waitForTimeout(6000);
console.log('MAP zoom control', JSON.stringify(await p.evaluate(()=>{const z=document.querySelector('.leaflet-control-zoom'); const t=document.querySelector('.map-surface button[aria-label="Map layers"]'); return z&&t?{zoomTop:Math.round(z.getBoundingClientRect().top), toolbarBottom:Math.round(t.getBoundingClientRect().bottom)}:null;})));
await p.screenshot({path:`${OUT}v16-map.png`, clip:{x:0,y:250,width:900,height:500}});
await p.goto(HOST+'/catches/new',{waitUntil:'load',timeout:60000}); await passChallenge(p); await p.waitForTimeout(4000);
console.log('FORM placeholders', JSON.stringify(await p.$$eval('#length, #weight', is=>is.map(i=>i.placeholder))));
await b.close();
